export const GAME_CONSTANTS = {
  BLITZ_DEFAULT_TIMER_SECONDS: 30,
  BLITZ_DEFAULT_POINTS: 10,
  BLITZ_MIN_POINTS_IF_CORRECT: 1,

  TILE_BLITZ_DEFAULT_TIMER_SECONDS: 30,
  TILE_BLITZ_DEFAULT_POINTS: 10,
  TILE_BLITZ_DEFAULT_BONUS_POINTS: 5,

  UC_DEFAULT_TIMER_SECONDS: 60,
  UC_DEFAULT_POINTS_PER_CORRECT: 5,

  CLUE_REVEAL_DEFAULT_CLUE_TIMER_SECONDS: 15,
  CLUE_REVEAL_DEFAULT_POINTS: 10,
  CLUE_REVEAL_PENALTY_PER_CLUE: 2,
  CLUE_REVEAL_MIN_POINTS: 2,
  CLUE_REVEAL_DEFAULT_CLUE_COUNT: 4,

  STEAL_HOT_SEAT_TIMER_SECONDS: 30,
  STEAL_WINDOW_SECONDS: 10,

  HOT_SEAT_DEFAULT_TIMER_SECONDS: 45,

  LIGHTNING_ROUND_DURATION_SECONDS: 90,

  TRUE_FALSE_TIMER_SECONDS: 10,

  AUDIENCE_VOTE_DEFAULT_SECONDS: 30,
  AUDIENCE_VOTE_MIN_SECONDS: 20,
  AUDIENCE_VOTE_MAX_SECONDS: 40,

  QUESTION_PREDICTION_WINDOW_SECONDS: 8,

  DEFAULT_FUZZY_THRESHOLD: 0.85,
  AUDIENCE_CODE_LENGTH: 6,
  TEAM_PIN_LENGTH: 4,
  MODERATOR_PIN_LENGTH: 4,

  MAX_TEAM_MEMBERS: 3,
  MAX_NICKNAME_LENGTH: 20,
  MAX_MCQ_OPTIONS: 4,

  AUDIENCE_RANKING_POINTS_PER_CORRECT_POSITION: 1,
  AUDIENCE_QUESTION_PREDICTION_POINTS: 2,
  AUDIENCE_GHOST_ANSWER_POINTS: 3,
  AUDIENCE_CLUE_DEPTH_POINTS: 4,

  SCORE_QUESTION_SUMMARY_DISPLAY_MS: 4000,

  FRONTEND_DEV_PORT: 3003,
  BACKEND_PORT: 3002,
} as const

export const TEAM_COLORS = [
  '#3B82F6',
  '#EF4444',
  '#22C55E',
  '#F59E0B',
  '#A855F7',
  '#EC4899',
  '#14B8A6',
  '#F97316',
] as const
